<?php


$this->gridForm()->addHeader($this->form, array(
    'elements'              => array('title')
));

$this->gridForm()->addMain($this->form, array(
    'label'                 => $this->translate('override info'),
    'elements'              => array('link', 'link_label', 'cover', 'description', 'body')
));

//$this->gridForm()->addAside($this->form, array(
    //'label'                 => $this->translate('Highlighted content'),
    //'elements'              => array('info_content')
//));

echo $this->partial('grid/_form.phtml', $this);
