<?php
    if(isset($this->backUrl)) {
        $this->placeholder('headling_1')->set('<h1>Manage highlist of: <a href="'.$this->backUrl.'">'.$this->container->title.'</a></h1>');
    }
    else {
        $this->placeholder('headling_1')->set('<h1>Manage highlights of: ' . $this->container->title . '</h1>');
    }
?>
<style type="text/css">
    .hl-item {width: 275px; height: 100px;}
</style>
<?php $this->headScript()->captureStart(); ?>

$(function() {
    $("a.help-add, a.help-edit").click(function() {
        $(".hl-template").find(".hl-item").removeClass("hl-item-select");
        $$ = $(this).parent().parent().parent(); // box highlight selected
        $$.addClass("hl-item-select");
        $("fieldset")
            .show()
            .find('input[name=position]').val($$.attr("id").substr(8,2));
        
        selectedPosition = $$.attr("id").substr(8,2);
        return false;
     });
     
     $("#sortable").CUI('sortable', 
        { 
            update : function () { 
              $("#order", $("#orderForm")).val($('#sortable').sortable('serialize')); 
              $("#save-order").removeAttr('disabled');
            },
            cursor: 'crosshair',
            handle: $('li:not(.not-sortable)')
          }
    );
});

$(function(){
    $('#autocomplete').CUI('autocomplete', {
       source: "<?php echo $this->url(array('action' => 'autocomplete', 'id' => $this->container->id));?>",
       select: function(event, rws) {
          var form = this.form;
          $("#pk", form).val(rws.item.pk);
          $("#model", form).val(rws.item.model);
          $("input[name=proxy_pk]", form).val(rws.item.pk);
          $("input[name=proxy_content_type_id]", form).val(rws.item.model);
       }
    });
});

var url = {'article' : "<?php echo $this->url(array('module' => 'vinsoc', 'controller' => 'admin-article', 'action' => 'new', '_next' => $this->url(array('id' => $this->container->id, 'action' => 'add', 'position' => '___position___', 'pk' => '___pk___', 'model' => 'Vinsoc_Model_DbTable_Row_Article', 'returnto' => $this->url()))))?>"
        };
      
      
$(function(){
    $("#highlightCreate").live('click', function(){
        $(this).attr('href', url[$('#highlight-model').val()].replace('___position___', selectedPosition));
        
        return true;
    });
});



<?php $this->headScript()->captureEnd(); ?>

    <?php echo $this->autoCompleteForm ?>
    <div>
        <form id="formAutocomplete" class="form form-highlight" method="post" action="<?php echo $this->url(array('action' => 'add', 'id' => $this->container->id, 'returnto' => $this->url()));?>" >
            <fieldset>
                <legend><?php echo $this->translate('Add a highlight@backoffice,vinsoc')?></legend>
                <div class="float-left">
                    <input type="hidden" name="position" id="position" value="" />
                    <h3><?php echo $this->translate('Choose a content@backoffice,vinsoc')?></h3>
                    <input type="text" value="" id="autocomplete" name="autocomplete" value=""
                    class="ui-autocomplete-input ui-autocomplete-loading" role="textbox" aria-haspopup="true">
                    <input type="hidden" value="" id="model" name="model">
                    <input type="hidden" value="" id="pk" name="pk">
                    <input class="_add" type="submit" value="Add"><div class="clear"></div>
                </div>
                <div style="margin-left:400px;"> 
                    <h3>... or create one</h3>
                    <select class="select-normal" name="type" style="margin:5px 0" id="highlight-model">
                            <option value="article">Article</option>
                    </select>
                    <a id="highlightCreate" class="btn btn-normal-nicy" href="#"><span class="btn-style btn-bg-gray btn-txt-black btn-icon-black"><span class="btn-icon plus"></span> <?php echo $this->translate('Create@backoffice,highlight')?></span></a>                    
                </div>                
            </fieldset>
        </form>
    </div>
    <div>
        <form action="<?php echo $this->url(array('action' => 'save-order', 'id' => $this->container->id, 'returnto' => $this->url()));?>" method="post" id="orderForm">
            <ul class="hl-template" id="sortable">
                <?php
                $row_set = array();
                $maxPosition = 0;
                foreach ($this->container->row_set as $row) :
                $maxPosition = max($maxPosition, $row->position);
                ?>
                    <li class="hl-item" id="hl-item-<?php echo ($row->position);?>" style="position:relative">
                        <?php if ($row === null): ?>
                        <em>Empty</em>
                        <?php else: ?>
                        <input type="hidden" name="rowId[]" value="<?php echo $row->id?>" />
                        <h3><?php echo $this->container->getTitle($row->getProxy());?></h3>
                        <?php endif; ?>
                        <ul class="actions">
                            <li><a href="#" class="help help-edit" title="Edit"><span class="ui-icon ui-icon-pencil">Edit</span></a></li>
                            <?php if ($row !== null): ?>
                            <li><a href="<?php echo $this->url(array('row_id' => $row->id, 'action' => 'delete', 'returnto' => $this->url()));?>" class="help help-remove" title="Remove" onclick="return confirm('<?php echo $this->translate('Are you sure to do this ?');?>');"><span class="ui-icon ui-icon-close">Remove</span></a></li>
                            <?php endif;?>
                        </ul>    
                    </li>
                <?php endforeach; ?>
                
                    <li class="hl-item not-sortable" id="hl-item-<?php echo ($maxPosition + 1);?>" style="position:relative">
                        <em><?php echo $this->translate('Empty@backoffice,vinsoc')?></em>
                        <ul class="actions">
                            <li><a href="#" class="help help-edit" title="Edit"><span class="ui-icon ui-icon-pencil"><?php echo $this->translate('Edit@backoffice,vinsoc')?></span></a></li>
                        </ul>
                    </li>
            </ul>
            <div class="save-order">
                <div class="pager">
                    <div class="pager-links">
                        <div class="pager-info">
                            <input type="submit" value="Save new order" disabled id="save-order" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="clear">&nbsp;</div>
        </form>
    </div>
