<?php
if(isset($this->proxy)) {
    $this->placeholder('headling_1')->set('<h1>Manage highlights of: ' . $this->smartTextCrop($this->proxy->__toString(), 60) . '</h1>');
}
else {
    $this->placeholder('headling_1')->set('<h1>Manage named highlights</h1>');
}
?>
<ul>
<?php foreach ($this->containers as $container) : ?>
    <li>
    <a href="<?php echo $this->url(array('action' => 'get', 'id' => $container->id))?>"> <?php echo $container->title ?></a><br />
    </li>
<?php endforeach ?>
</ul>
